### ISSUE TITLE
Site não servido corretamente

### ISSUE THREAD

**Issue by meu-bem** [PyNorte/pynorte2024-site#1]
Opa, @Azanniel. Tudo bem? Vi que tu tocaste a parte do workflow site da Python Norte de 2023. Eu tentei reproduzir pra esse ano, mas parece que a página não está sendo servida corretamente. Quando eu digo isso, me refiro ao fato do app ter sido buildado corretamente pelo GitHub actions, mas quando acesso o endereço da página, as informações que deveriam ser providas pelo arquivo JS não alimentam a div root. Testei localmente rodando um servidor local com `python -m http.server` no diretório `dist/`, e consegui acessar normalmente o app. Podes me dar uma mão?

Atual endereço: https://pynorte.github.io/pynorte2024-site/

**Comment by meu-bem** [comment]
Estou fechando essa issue porque o problema se resolveu. Acho que era cache. 😅
No entanto, fica o convite pra trabalhar no site desse ano. As contribuições serão mais que bem-vindas!

**Comment by Azanniel** [comment]
Opa, perdão a demora, mas que bom que conseguiu resolver.
Agradeço pelo convite para contribuição também 💜
