### ISSUE TITLE
Criar seção "Nossos Contatos".

### ISSUE THREAD

**Issue by meu-bem** [PyNorte/pynorte2024-site#13]
Criar seção "Nossos Contatos" e integrar à página inicial.

Versão desktop: 
![image](https://github.com/PyNorte/pynorte2024-site/assets/69017381/3092c621-18a4-436d-bc15-2472521c9a42)

Versão mobile: 
![image](https://github.com/PyNorte/pynorte2024-site/assets/69017381/70452884-40be-4559-a09f-5e0e7aef07fd)

Os ícones utilizados vêm da biblioteca [Lucide Icons](https://lucide.dev/guide/packages/lucide-react).

**Comment by fabiobrasileiroo** [comment]
**This issue has been closed:** https://github.com/PyNorte/pynorte2024-site/commit/ff1f2703c6b2ff557126219220f2361a4495abf7
