### ISSUE TITLE
Atualizar o readme desse ano.

### ISSUE THREAD

**Issue by meu-bem** [PyNorte/pynorte2024-site#15]
O projeto do site foi um fork do projeto do ano passado, por tanto, o arquivo [README.md](https://github.com/PyNorte/pynorte2024-site/blob/main/README.md) precisa ser atualizado com os links e informações desse ano.

**Comment by meu-bem** [comment]
@Azanniel, pegaste esse? Podes fechar?

**Comment by Azanniel** [comment]
Tive que remover algumas coisas, pois estavam obsoletas para o site desse ano, mas posso incrementar esse novo README com quaisquer informações que sejam relevantes.
