### ISSUE TITLE
Criar post e postar sobre o ICET/UFAM.

### ISSUE THREAD

**Issue by meu-bem** [PyNorte/pynorte2024-site#20]
O ICET/UFAM é nosso apoiador nessa edição, enfatizar isso no post. E será nele que ocorrerá o nosso evento.

Assim que tiver o texto finalizado, passar as informações para o time de Design no Discord produzir as imagens.

**Comment by Neill-Ataide** [comment]
🐍🔥 Saudações, já estão ligados no local que ocorrerá a Python Norte 2024?! 🔥🐍

Um dos maiores eventos de tecnologia e programação da região! Este ano, o evento será realizado no auditório da Universidade Federal do Amazonas (UFAM), nosso grande apoiador. A UFAM é reconhecida por seu compromisso com a inovação, excelência acadêmica e desenvolvimento científico, proporcionando um ambiente ideal para este grande encontro.

📍 Endereço:
Nossa Senhora do Rosário, 3863 - Bairro Tiradentes (Em frente à Escola SESI)

🚀 Não perca esta chance de fazer parte de uma comunidade vibrante e em constante crescimento! 🌟 Junte-se a nós no Python Norte 2024 e leve seu conhecimento para o próximo nível. 💡

#PythonNorte #Python #ComunidadePython #Tecnologia #Programação #Aprendizado #EventosTech #eventotech #PythonBrasil #Negocios #Patrocinio #Empresas #EmpresasTech #Itacoatiara #UFAMItacoatiara
