### ISSUE TITLE
Criar seção sobre o cronograma.

### ISSUE THREAD

**Issue by meu-bem** [PyNorte/pynorte2024-site#21]
Criar seção pra mostrar que as submissões estão abertas.

![Image](https://github.com/PyNorte/pynorte2024-site/assets/69017381/e2590299-d7a1-42cb-846d-f5be19758b45)

**Comment by meu-bem** [comment]
Utilizar os [informações do ano passado](https://2023.pythonnorte.org/).

**Comment by Azanniel** [comment]
Utilizar esse recurso para redirecionamento ao clicar no botão:

https://docs.google.com/forms/d/e/1FAIpQLSftmJ6pNJ7qPgKfNre0ebT5zGgHtyIMiyoZVr1Aj24t-7BPag/viewform
