### ISSUE TITLE
Criar sessão "Patrocinadores".

### ISSUE THREAD

**Issue by meu-bem** [PyNorte/pynorte2024-site#22]
* Nessa sessão deve conter as três categorias: Ouro, Prata e Bronze. Além da categoria de "Apoio".
* Só devem ser exibidas as categoria que contenham algo. Por exemplo, se só temos apoio e patrocinador ouro, apenas essas categorias devem ser exibidas.
* As imagens devem levar à página do Patrocinador.

![Image](https://github.com/PyNorte/pynorte2024-site/assets/69017381/b5c3df5e-df30-4dd1-aa3d-0237f6730c29)

**Comment by meu-bem** [comment]
O único patrocinador que temos no momento é o ICET/UFAM.


![Image](https://github.com/PyNorte/pynorte2024-site/assets/69017381/42014daf-e895-4d9c-a7ad-d2b38551fce5)

**Comment by Elian-beep** [comment]
Qual a categoria de ICET/UFAM?

**Comment by meu-bem** [comment]
Apoio!
