### ISSUE TITLE
Postergado período de submissões até o dia 29/05

### ISSUE THREAD

**Issue by meu-bem** [PyNorte/pynorte2024-site#25]
![Image](https://github.com/PyNorte/pynorte2024-site/assets/69017381/e27d75a6-3d23-4655-bb6b-b075af259662)

**Comment by Neill-Ataide** [comment]
🐍🔥 Faça parte da Python Norte 2024! 🔥🐍

📅 ATENÇÃO: O prazo de inscrições foi postergado! 📅

✅ Nova data: Inscrições até 29/05 ✅

Agora, você tem até o dia 29 de maio para inscrever suas atividades na Python Norte 2024. Não perca essa oportunidade de compartilhar seu conhecimento e fazer parte deste evento incrível!

🔗 Inscreva-se agora e garanta sua participação: https://t.co/WAdGg46VIp

Aguardamos suas inscrições! Vamos fazer da Python Norte 2024 um evento inesquecível!

#PythonNorte2024 #ComunidadePython #InscriçõesAbertas
