### ISSUE TITLE
Atualizar o header do site.

### ISSUE THREAD

**Issue by meu-bem** [PyNorte/pynorte2024-site#5]
Versão desktop: 
![image](https://github.com/PyNorte/pynorte2024-site/assets/69017381/cc4a9c2e-b097-4e12-81e2-697dc56eeb42)

Versão mobile: 
![image](https://github.com/PyNorte/pynorte2024-site/assets/69017381/f28944ab-ee3b-4f56-b53e-2a8b9484b676)

Outra coisa que precisa ser feita nessa issue é a correção de um bug na versão mobile que está em produção. Quando a página está no topo, o fundo do menu não fica como deveria (na cor sunset-400). Exemplo:
![image](https://github.com/PyNorte/pynorte2024-site/assets/69017381/9281f68d-657d-4e9c-a854-90a121849a97)

**Comment by Azanniel** [comment]
Identifiquei esse bug também @MateusSantosMeuBem, trabalharei para solucionar esse problema.
