### ISSUE TITLE
Adicionar id para cada um dos elementos apontados em links dentro do proprio site

### ISSUE THREAD

**Issue by luzfcb** [PyNorte/pynorte2024-site#50]
Adicionar id para cada um dos elementos apontados em links dentro do proprio site.

Por exemplo, Local do evento tem um link que aponda para o elemento id "eventLocation" , contudo não existe nenhum elemento com esse id, e então o link https://2024.pythonnorte.org/#eventLocation não funciona conforme o esperado.

**Comment by fabiobrasileiroo** [comment]
This issue has been closed fix ◝(ᵔᗜᵔ)◜: https://github.com/PyNorte/pynorte2024-site/commit/4c52a8667775741a4b83174170bd35c9b466fe4e
