### ISSUE TITLE
Atualizar o footer do site.

### ISSUE THREAD

**Issue by meu-bem** [PyNorte/pynorte2024-site#6]
Versão desktop: 
![image](https://github.com/PyNorte/pynorte2024-site/assets/69017381/58570c88-75b2-4792-8f16-0f22d9b442a8)

Versão mobile: 
![image](https://github.com/PyNorte/pynorte2024-site/assets/69017381/3088517b-2675-479b-a466-fd40da843320)

Os ícones utilizados vêm da biblioteca [Lucide Icons](https://lucide.dev/guide/packages/lucide-react).

**Comment by Azanniel** [comment]
Quais seriam os links de redes sociais disponíveis para adicionar nas âncoras?

**Comment by Azanniel** [comment]
Adicionado em f1d3cf36dddc9afd792f57cf89889a5954d081fb
