### ISSUE TITLE
Botão de ação.

### ISSUE THREAD

**Issue by meu-bem** [PyNorte/pynorte2024-site#7]
Criar o botão de ação.
Prévia do Figma:
![image](https://github.com/PyNorte/pynorte2024-site/assets/69017381/6d48c36c-01d4-4c0a-815a-ae7d39c67648)

**Comment by Azanniel** [comment]
@MateusSantosMeuBem, queria saber se esse botão terá algum tipo de animação? Se sim, poderia me explicar como seria?

**Comment by Azanniel** [comment]
O botão foi adicionado, mas fico no aguardo para saber qual tipo de micro interação ou animação pode ter nesse botão.
