### ISSUE TITLE
Criar seção inicial.

### ISSUE THREAD

**Issue by meu-bem** [PyNorte/pynorte2024-site#8]
Criar seção inicial e integrar à página inicial.

Versão desktop: 
![image](https://github.com/PyNorte/pynorte2024-site/assets/69017381/6df33f21-619a-433c-b499-1aacf6185919)

Versão mobile: 
![image](https://github.com/PyNorte/pynorte2024-site/assets/69017381/3c5c1080-d8b5-463c-b65e-5d16a78d3225)

**Comment by Azanniel** [comment]
Adicionarei essa seção descritiva. Tentarei adicionar a imagem também se possível.

**Comment by Azanniel** [comment]
Adicionado em https://github.com/PyNorte/pynorte2024-site/commit/cb6c8422fd7a5fdf7e690996848ed3f9d19638e5
