### ISSUE TITLE
Criar a seção "sobre".

### ISSUE THREAD

**Issue by meu-bem** [PyNorte/pynorte2024-site#9]
Criar a seção "sobre" e integrar à página inicial.

Versão desktop: 
![image](https://github.com/PyNorte/pynorte2024-site/assets/69017381/1d4be049-6163-4735-b81a-462b5d0aecbd)

Versão mobile: 
![image](https://github.com/PyNorte/pynorte2024-site/assets/69017381/6604b7ac-be82-4f7c-a3c3-90097a54484c)

**Comment by Azanniel** [comment]
Adicionado em 9c274412562cc49707c72fe46df786d4f35ef81e
